name: Build LaTeX document
on: 
 push:
jobs:
 buildlatex:
  runs-on: ubuntu-latest
  container: texhackse/texlive-node-github
  steps:
   - run: echo "running texlive-node-github:latest"
   - name: Set up Git repository
     uses: actions/checkout@v3
   - name: build documents
     run: latexmk
   - name: upload pdfs
     uses: actions/upload-artifact@v3
     with:
       name: pdf-results
       path: |
         */*.pdf
	 */*/*.pdf

